Github API with Octokit
evrimagaci/periodum-api pull request #25
Opened 2022-04-14 03:29 UTC by goodluckgod

2022-04-14 12:26 UTC, nesimtunc commented
Hi @goodluckgod,

Thanks for the contribution. Can you please do things below. Thanks!

- [ ] Add a description to the PR
- [ ] Follow the existing architecture (Create a `GitHubService` and do the business logic inside there, then use it through the Controller
- [ ] Add some tests
- [ ] Ensure the existing tests are NOT failing.

2022-04-14 12:27 UTC, nesimtunc requested changes
Hi @goodluckgod,

Thanks for the contribution. Can you please do things below. Thanks!

- [ ] Add a description to the PR
- [ ] Follow the existing architecture (Create a `GitHubService` and do the business logic inside there, then use it through the Controller
- [ ] Add some tests
- [ ] Ensure the existing tests are NOT failing.

2022-04-15 00:57 UTC, nesimtunc commented on src/controllers/github.controller.ts
> +				'evrimagaci',
projects names are; 
 - `periodum`
 - `periodum-api`
 - `periodum-apple`

Maybe we can also provide these names as an array (can be split by `,`)  in `env` _variables`?

```bash
GITHUB_REPOS="periodum,periodum-api,periodum-apple"
```

In the future we might add new repos. So, we won't need to re-deploy the app but changing the env variable.

2022-04-15 00:59 UTC, nesimtunc commented on dev.env
> +GITHUB_TOKEN=
In here can you write Token's permission scope, please? It will be useful for us to generate it.

2022-04-15 01:06 UTC, dogukanduran commented on src/controllers/github.controller.ts
> +				'evrimagaci',
Nice idea! Also i will add env_variables to 'GITHUB_REPO_OWNER' for username.

2022-04-15 01:15 UTC, nesimtunc commented on test/pubchem/github.spec.ts
> +		const contributors = await githubService.getContributors(
This is integration test. What we need is unit testing, ensure the functionality of the service working as expected. Therefore you need to mock / stub your function, in other words, have the response and _assert_ that. 

For example a good test case would be like: Can service merge the repos and group by user?

2022-04-15 01:16 UTC, nesimtunc commented on test/pubchem/github.spec.ts
> +		const contributors = await githubService.getContributors(
Maybe in the future we can have integration test though. For now, it's okay not to have.

2022-04-15 01:19 UTC, nesimtunc commented on test/pubchem/github.spec.ts
> +		const contributors = await githubService.getContributors(
As an example or get the idea, you may check PubChem Import Script task's tests #16

2023-03-02 03:02 UTC, nesimtunc commented
Expired.

2023-03-02 03:02 UTC, closed without merging